//console.log("Hello World")
//console.log("Turma 2MIB")
//console.log("Turma \n\n\n 2MIB")
//console.log("NOME\tNOTA\t2MIC")
//console.log("Pedro\t10\t2MIC")
//console.log("Paulo\t09\t2MIC")
//console.log("Carla\t10\t2MIC")


//let nome = "Pedro"

//let valor1 = 10
//let valor2 = 20
//let valor3 = valor1 + valor2

//console.log("Oi meu amigo(a) "+nome.toLowerCase)
//console.log("A soma dos valores é : "+(valor1+valor2))

//let nome = "Pedro"

//var valor1 = 10
//var valor2 = 20
//var valor3 = valor1 + valor2

//console.log("Oi meu amigo(a) "+nome.toLowerCase)
//console.log("A soma dos valores é : "+(valor1+valor2))

//let numero = 0


//numero = leia("Digite um número : ")



//const leia = require("prompt-sync")()

//let numero1, numero2 = 0

//numero1 = leia("Digite um primeiro número : ")
//numero2 = leia("Digite um segundo número : ")
//console.log("A soma de "+numero1+" mais "+numero2+" é "+(numero1+numero2))





const leia = require("prompt-sync")()

let numero1, numero2 = 0

numero1 = parseInt(leia("Digite um primeiro número : "))
numero2 = parseInt(leia("Digite um segundo número : "))
console.log("A soma de "+numero1+" mais "+numero2+" é "+(numero1+numero2))